ServisUygulama/ServisUygulama/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ServisUygulama.Models;

namespace ServisUygulama.Controllers
{
    public class BrandsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Brands
        [Authorize]
        public async Task<ActionResult> Index()
        {
            return View(await db.Brands.ToListAsync());
        }

        // GET: Brands/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = await db.Brands.FindAsync(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: Brands/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create([Bind(Include = "BrandID,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: Brands/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = await db.Brands.FindAsync(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "BrandID,BrandName")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: Brands/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = await db.Brands.FindAsync(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Brand brand = await db.Brands.FindAsync(id);
            db.Brands.Remove(brand);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ServisUygulama/ServisUygulama/Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ServisUygulama.Models;

namespace ServisUygulama.Controllers
{
    public class DriversController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Drivers
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var drivers = db.Drivers.Include(d => d.City);
            return View(await drivers.ToListAsync());
        }

        // GET: Drivers/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = await db.Drivers.FindAsync(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // GET: Drivers/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name");
            return View();
        }

        // POST: Drivers/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create([Bind(Include = "DriverID,DriverName,Phone,BirthDate,CityID")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                db.Drivers.Add(driver);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name", driver.CityID);
            return View(driver);
        }

        // GET: Drivers/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = await db.Drivers.FindAsync(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name", driver.CityID);
            return View(driver);
        }

        // POST: Drivers/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "DriverID,DriverName,Phone,BirthDate,CityID")] Driver driver)
        {
            if (ModelState.IsValid)
            {
                db.Entry(driver).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CityID = new SelectList(db.Cities, "CityID", "Name", driver.CityID);
            return View(driver);
        }

        // GET: Drivers/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Driver driver = await db.Drivers.FindAsync(id);
            if (driver == null)
            {
                return HttpNotFound();
            }
            return View(driver);
        }

        // POST: Drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Driver driver = await db.Drivers.FindAsync(id);
            db.Drivers.Remove(driver);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ServisUygulama/ServisUygulama/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using ServisUygulama.Models;
using System.Threading.Tasks;

namespace ServisUygulama.Controllers
{
    public class RoleController : Controller
    {
        private ApplicationRoleManager _roleManager;

        public RoleController()
        {
        }

        public RoleController(ApplicationRoleManager roleManager)
        {
            RoleManager = roleManager;
        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        // GET: Role
        [Authorize]
        public ActionResult Index()
        {
            List<RoleViewModel> list = new List<RoleViewModel>();
            foreach (var role in RoleManager.Roles)
            {
                list.Add(new RoleViewModel(role));
            }
            return View(list);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create(RoleViewModel model)
        {
            var role = new ApplicationRole() { Name = model.Name };
            await RoleManager.CreateAsync(role);
            return RedirectToAction("Index");

        }
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(RoleViewModel model)
        {
            var role = new ApplicationRole() { Id = model.Id, Name = model.Name };
            await RoleManager.UpdateAsync(role);
            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<ActionResult> Details(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            return View(new RoleViewModel(role));
        }
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            await RoleManager.DeleteAsync(role);
            return RedirectToAction("Index");
        }
       

    }
}

ServisUygulama/ServisUygulama/Controllers/SchoolBusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ServisUygulama.Models;

namespace ServisUygulama.Controllers
{
    public class SchoolBusController : Controller
    {
        public ApplicationDbContext db = new ApplicationDbContext();

        // GET: SchoolBus
        [Authorize]
        public async Task<ActionResult> Index()
        {
            var schoolBus = db.SchoolBus.Include(s => s.Brand).Include(s => s.Driver);
            return View(await schoolBus.ToListAsync());
        }

        // GET: SchoolBus/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolBus schoolBus = await db.SchoolBus.FindAsync(id);
            db.SchoolBus.Include(x => x.Brand).Include(x => x.Driver).ToList();
            
            if (schoolBus == null)
            {
                return HttpNotFound();
            }
            return View(schoolBus);
        }

        // GET: SchoolBus/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.MarkaID = new SelectList(db.Brands, "BrandID", "BrandName");
            ViewBag.DriverID = new SelectList(db.Drivers, "DriverID", "DriverName");
            return View();
        }

        // POST: SchoolBus/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "BusID,Plate,Model,KoltukSayısı,DriverID,MarkaID")] SchoolBus schoolBus)
        {
            if (ModelState.IsValid)
            {
                db.SchoolBus.Add(schoolBus);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.MarkaID = new SelectList(db.Brands, "BrandID", "BrandName", schoolBus.MarkaID);
            ViewBag.DriverID = new SelectList(db.Drivers, "DriverID", "DriverName", schoolBus.DriverID);
            return View(schoolBus);
        }

        // GET: SchoolBus/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolBus schoolBus = await db.SchoolBus.FindAsync(id);
            if (schoolBus == null)
            {
                return HttpNotFound();
            }
            ViewBag.MarkaID = new SelectList(db.Brands, "BrandID", "BrandName", schoolBus.MarkaID);
            ViewBag.DriverID = new SelectList(db.Drivers, "DriverID", "DriverName", schoolBus.DriverID);
            return View(schoolBus);
        }

        // POST: SchoolBus/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit([Bind(Include = "BusID,Plate,Model,KoltukSayısı,DriverID,MarkaID")] SchoolBus schoolBus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(schoolBus).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.MarkaID = new SelectList(db.Brands, "BrandID", "BrandName", schoolBus.MarkaID);
            ViewBag.DriverID = new SelectList(db.Drivers, "DriverID", "DriverName", schoolBus.DriverID);
            return View(schoolBus);
        }

        // GET: SchoolBus/KayitOl/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> KayitOl(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
            
        }


        // GET: SchoolBus/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolBus schoolBus = await db.SchoolBus.FindAsync(id);
            if (schoolBus == null)
            {
                return HttpNotFound();
            }
            return View(schoolBus);
        }

        // POST: SchoolBus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            SchoolBus schoolBus = await db.SchoolBus.FindAsync(id);
            db.SchoolBus.Remove(schoolBus);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ServisUygulama/ServisUygulama/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>ServisHQ - Her şey yolunda.</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        @Html.Partial("navbar")
        <div id="page-wrapper" style="min-height: 340px;">
            @RenderBody()
        
        </div>
            <!-- /#page-wrapper -->
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

ServisUygulama/ServisUygulama/Views/Shared/navbar.cshtml
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink(ServisUygulama.Resources.HomeTexts.ApplicationName, "Index", "Home",null, htmlAttributes: new { @class = "navbar-brand" })
    </div>
    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links navbar-right">
        
       
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <a href="~/Manage/Index"><i class="fa fa-user fa-fw"></i>@ServisUygulama.Resources.HomeTexts.Userprofil</a>
                </li>
               
                <li class="divider"></li>
                <li>
                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                    {
                    @Html.AntiForgeryToken()
                        <a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-sign-out fa-fw"></i>Oturumu kapat</a>
                    }
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-globe fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    @Html.ActionLink(ServisUygulama.Resources.HomeTexts.Turkish, "Change", "Home", new { LanguageAbbrevation = "tr", returnUrl = Request.RawUrl }, null)
                </li>

                <li>
                    @Html.ActionLink(ServisUygulama.Resources.HomeTexts.English, "Change", "Home", new { LanguageAbbrevation = "en", returnUrl = Request.RawUrl }, null)</a>
                </li>
                <li class="divider"></li>

            </ul>

            <!-- /.dropdown-user -->
        </li>
    </ul>
    <!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                
                <li>
                    @Html.ActionLink(ServisUygulama.Resources.HomeTexts.Home, "Index", "Home")
                </li>
                
                
                
                
                <li>
                    <a href="#"><i class="fa fa-sitemap fa-fw"></i> @ServisUygulama.Resources.HomeTexts.Services <span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        @if (User.IsInRole("Admin"))
                        { 
                        <li>
                            @Html.ActionLink(ServisUygulama.Resources.HomeTexts.AddService, "Create", "SchoolBus")
                        </li>
                        }
                        <li>
                            @Html.ActionLink(ServisUygulama.Resources.HomeTexts.Lists, "Index", "SchoolBus")
                        </li>
                        <li>
                            <a href="#">@ServisUygulama.Resources.HomeTexts.Brands <span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                                @if (User.IsInRole("Admin"))
                                {
                                <li>
                                    @Html.ActionLink(ServisUygulama.Resources.HomeTexts.AddBrand, "Create", "Brands")
                                </li>
                                }
                                <li>
                                    @Html.ActionLink(ServisUygulama.Resources.HomeTexts.Lists, "Index", "Brands")
                                </li>
                                
                            </ul>
                            <!-- /.nav-third-level -->
                        </li>
                        <li>
                            <a href="#">@ServisUygulama.Resources.HomeTexts.Drivers<span class="fa arrow"></span></a>
                            <ul class="nav nav-third-level">
                               @if (User.IsInRole("Admin"))
                               {
                                   <li>
                                    @Html.ActionLink(ServisUygulama.Resources.HomeTexts.AddDriver, "Create", "Drivers")
                                </li>
                               }
                                <li>
                                    @Html.ActionLink(ServisUygulama.Resources.HomeTexts.Lists, "Index", "Drivers")
                                </li>
                                
                            </ul>
                            <!-- /.nav-third-level -->
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-users"></i>@ServisUygulama.Resources.HomeTexts.Roller<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                       @if (User.IsInRole("Admin"))
                       {
                        <li>
                            @Html.ActionLink(ServisUygulama.Resources.HomeTexts.CreateRole, "Create", "Role")
                        </li>
                       }
                        <li>
                            @Html.ActionLink(ServisUygulama.Resources.HomeTexts.Lists, "Index", "Role")
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-graduation-cap"></i>@ServisUygulama.Resources.HomeTexts.Schools<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        @if (User.IsInRole("Admin"))
                        {
                        <li>
                            @Html.ActionLink(ServisUygulama.Resources.HomeTexts.CreateSchool, "Create", "Universities")
                        </li>
                        }
                        <li>
                            @Html.ActionLink(ServisUygulama.Resources.HomeTexts.Lists, "Index", "Universities")
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
@if (User.IsInRole("Admin"))
{
                <li>
                    <a href="#"><i class="fa fa-list-ul"></i>@ServisUygulama.Resources.HomeTexts.Students<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">

                        <li>
                            @Html.ActionLink(ServisUygulama.Resources.HomeTexts.Lists, "OgrenciList", "Home")
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
}

                <li>
                    <a href="#"><i class="fa fa-bullhorn"></i> @ServisUygulama.Resources.HomeTexts.Announcements<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">

                        <li>
                            @Html.ActionLink(ServisUygulama.Resources.HomeTexts.Lists, "Index", "Announcements")
                        </li>
                         @if (User.IsInRole("Admin"))
                         {
                        <li>
                            @Html.ActionLink(ServisUygulama.Resources.HomeTexts.AddAnnouncement, "Create", "Announcements")
                        </li>
                         }
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>